server:
  port: 8089

spring:
  application:
    name: shoppingcar #对外暴露的服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: 购物车服务-8082 #人性化显示出服务的信息
    prefer-ip-address: true     #访问路径可显示ip地址
#    用来展示基本信息
info:
  author.name: lin
  app.name: shoppingCarConsumer
  server.port: ${server.port}
  application.name: ${spring.application.name}

