server:
  port: 8096

spring:
  application:
    name: cm-java #对外暴露的服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: boss-8096 #人性化显示出服务的信息
    prefer-ip-address: true     #访问路径可显示ip地址
#    用来展示基本信息
info:
  author.name: shi
  app.name: cm-java
  server.port: ${server.port}
  application.name: ${spring.application.name}

