server:
  port: 8095

spring:
  application:
    name: staffClient #对外暴露的服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: 员工服务-8095 #人性化显示出服务的信息
    prefer-ip-address: true     #访问路径可显示ip地址
#    用来展示基本信息
info:
  author.name: zhang
  app.name: staffClient
  server.port: ${server.port}
  application.name: ${spring.application.name}

