server:
  port: 8083

spring:
  application:
    name: orderconsumer #对外暴露的服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: 订单服务-8083  #人性化显示出服务的信息
    prefer-ip-address: true     #访问路径可显示ip地址
#    用来展示基本信息
info:
  author.name: shengwu ni
  app.name: orderconsumer
  server.port: ${server.port}
  application.name: ${spring.application.name}

